### PR TITLE
Joshua's Changes from 5/4 - 28

### PR DESCRIPTION
**Pull request by joshua9889**
Changes:
- Main Change: Got trajectory generation and following to work on the physical robot!
- Found the problem with the profile being one order lower - the largest term, in this case kV, has the most impact on the output. kV = (1/max vel) and kA = (1/max acc)
- Deprecated old auto modes
- Remove unused files
- Added OpMode to see how much text is displayed per line
    Made the app compile
- Added PhoneFileReader which allows for the changing of constants on-the-fly. The constants are reloaded once every time the app is opened. Store the constants in Constants.java.
- Added classes to make path generation easier. Classes made: AppendPaths, Arc, Line, PointTurn, and ScalePath
- Added Excel file to show the plot of position/time of a simple profile
- Added Excel file to show how kV and kA where found, also shows how we adjusted the values to make the best constants possible.
- Changed FollowerConfig to not support kI
- Changed Drive zeroSensors to have the gyros reeeeset the Z axis

### CODE REVIEW

**Comment by joshua9889** [comment]
@TeamOverdrive I cannot resolve the file conflicts, because I don't have ownership of the repo. Please merge the changes that I made into the repo. Thanks!

**Comment by david-wzheng** [comment]
Ok.

**Review by david-wzheng — APPROVED** [review]
Ok.

**Comment by david-wzheng** [comment]
ugh have to perform a manual merge

**Review by david-wzheng — APPROVED** [review]
Ok.

**Comment by david-wzheng** [comment]
Reeeeeeeeeeeeeee can you fix this @joshua9889?
The classes from your merging branch should be replacing the old one right?

**Comment by joshua9889** [comment]
Ok I will try. REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE git

**Comment by david-wzheng** [comment]
does the work hmmmmmmmmmmmmmmmmm?

**Comment by david-wzheng** [comment]
well merged it

**Pull request merged**
